[mgr]
show_hidden = true

[opener]
edit = [
  { run = "${EDITOR:-nvim} %s", desc = "$EDITOR", for = "unix", block = true },
]
play = [
  { run = "xdg-open %s1", desc = "Play", for = "linux", orphan = true },
  { run = "open %s", desc = "Play", for = "macos" },
]
open = [
  { run = "xdg-open %s1", desc = "Open", for = "linux" },
  { run = "open %s", desc = "Open", for = "macos" },
]
reveal = [
  { run = "xdg-open %d1", desc = "Reveal", for = "linux" },
  { run = "open -R %s1", desc = "Reveal", for = "macos" },
]
extract = [
  { run = "ya pub extract --list %s", desc = "Extract here" },
]
trash = [
  { run = "ya pub trash-restore --list %S", desc = "Restore selected files" },
  { run = "ya pub trash-empty --list %S",   desc = "Empty trash bin" },
]

[open]
rules = [
  { mime = "folder/*", use = [ "reveal" ] },
  { mime = "text/*", use = [ "edit", "reveal" ] },
  { mime = "image/*", use = [ "open", "reveal" ] },
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
  { mime = "trash/**", use = [ "open", "trash" ] },
	{ url = "*", use = [ "open", "reveal" ] },
]
