# theme
include tokyo-night.conf

# keys
map ctrl+page_up previous_tab
map ctrl+page_down next_tab

# font
font_family Office Code Pro
italic_font Office Code Pro Regular Italic
bold_font Office Code Pro Bold
bold_italic_font Office Code Pro Bold Italic
text_composition_strategy legacy
font_size 20

# tab bar
tab_bar_background #16161e
tab_bar_edge top
tab_bar_align center
tab_bar_style powerline
active_tab_foreground #bec8f3
active_tab_background #3b4261
active_tab_font_style normal
inactive_tab_foreground #737aa2
inactive_tab_background #16161e
inactive_tab_font_style normal

# all support
placement_strategy top-left
remember_window_size no

# macos support
map super+a send_text all \x1ba
map super+b send_text all \x1bb
map super+c send_text all \x1bc
map super+d send_text all \x1bd
map super+e send_text all \x1be
map super+f send_text all \x1bf
map super+h send_text all \x1bh
map super+j send_text all \x1bj
map super+k send_text all \x1bk
map super+l send_text all \x1bl
map super+m send_text all \x1bm
map super+n send_text all \x1bn
map super+p send_text all \x1bp
map super+q send_text all \x1bq
map super+r send_text all \x1br
map super+s send_text all \x1bs
map super+t send_text all \x1bt
map super+u send_text all \x1bu
map super+v send_text all \x1bv
map super+w send_text all \x1bw
map super+x send_text all \x1bx
map super+y send_text all \x1by
map super+z send_text all \x1bz

