# startup
set -g base-index 1
set -g prefix C-Space

# leader
unbind C-b
unbind C-Enter
bind C-Space send-prefix

# rename
unbind ,
bind r command-prompt "rename-window '%%'"

# reload
bind , source-file ~/.tmux.conf
bind < run '~/.tmux/plugins/tpm/bin/install_plugins'

# clear
bind "'" send-keys C-l

# number
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# extend
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g mouse on

# linux support
bind-key -n C-PageUp previous-window
bind-key -n C-PageDown next-window

# macos support
bind-key -n 'M-{' previous-window
bind-key -n 'M-}' next-window

# windows
bind-key [ swap-window -t -1\; select-window -t -1
bind-key ] swap-window -t +1\; select-window -t +1
unbind &
bind X confirm-before -p "kill-window #W? (y/n)" kill-window
unbind '%'
unbind '"'
bind v split-window -h
bind s split-window -v

# panes
bind h swap-pane -s '{left-of}'
bind j swap-pane -s '{down-of}'
bind k swap-pane -s '{up-of}'
bind l swap-pane -s '{right-of}'
bind J break-pane -a
bind K break-pane -b
bind H move-pane -t :-
bind L move-pane -t :+
unbind m
bind -n C-m resize-pane -Z
unbind C-Space
bind C-Space select-pane -t :.+

# layouts
unbind -
bind - resize-pane -x 75% -y 75%
unbind =
bind = select-layout -E

# plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor 'moonlight_dark'

run '~/.tmux/plugins/tpm/tpm'

# colors
set -g pane-active-border-style "fg=#66023c"
set -g pane-border-style "fg=#33011e"

# nvim-tmux-navigation
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi 'C-h' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' 'select-pane -R'

display-message "TMUX config reloaded."

