# startup
set -g base-index 1
set -g prefix C-Space

# leader
unbind C-b
unbind C-Enter
bind C-Space send-prefix

# rename
unbind ,
bind r command-prompt -I "#W" "rename-window '%%'"

# reload
bind , source-file ~/.tmux.conf
bind < run '~/.tmux/plugins/tpm/bin/install_plugins'

# number
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# extend
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'
set -g mouse on

# windows
bind-key '[' previous-window
bind-key ']' next-window
bind-key '{' swap-window -t -1\; select-window -t -1
bind-key '}' swap-window -t +1\; select-window -t +1

# panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H swap-pane -s '{left-of}' \; select-pane -L
bind J swap-pane -s '{down-of}' \; select-pane -D
bind K swap-pane -s '{up-of}' \; select-pane -U
bind L swap-pane -s '{right-of}' \; select-pane -R
unbind m
bind m resize-pane -Z
unbind &
bind X confirm-before -p "kill-window #W? (y/n)" kill-window
unbind o
bind C-Space select-pane -t :.+
unbind '%'
unbind '"'
bind v split-window -h
bind s split-window -v

# plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor 'moonlight_dark'

run '~/.tmux/plugins/tpm/tpm'
display-message "TMUX config reloaded."

