# startup
set -s extended-keys on
set -s extended-keys-format csi-u
set -g focus-events on
set -g mouse on
setw -g mode-keys vi

# leader
set -g prefix C-Space
bind 'C-Space' 'send-prefix'
bind ',' 'source-file ~/.tmux.conf'
bind '<' 'run ~/.tmux/plugins/tpm/bin/install_plugins'

# yazi support
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# linux support
unbind 'C-Enter'
bind-key -n 'C-PageUp' 'previous-window'
bind-key -n 'C-PageDown' 'next-window'

# macos support
bind-key -n 'M-[' 'previous-window'
# bind-key -n 'M-]' 'next-window'
bind-key -n 'M-{' 'previous-window'
bind-key -n 'M-}' 'next-window'

# sessions
bind 'q' 'choose-tree -s'
bind 'R' command-prompt "rename-session '%%'"

# windows
set-option -g renumber-windows on
bind-key '[' 'swap-window -d -t -1'
bind-key ']' 'swap-window -d -t +1'
bind c new-window -a
bind m new-window -a 'tmux rename-window mx; cmatrix'
bind x if-shell -F '#{m/r:(sh|bash|zsh),#{pane_current_command}}' \
    'kill-pane' \
    'confirm-before -p "kill-pane #P? (y/n)" "kill-pane"'
bind 'X' confirm-before -p "kill-window #W? (y/n)" 'kill-window'
bind 'r' command-prompt "rename-window '%%'"

# panes
set -g base-index 1
setw -g pane-base-index 1
bind 'v' 'split-window -h'
bind 's' 'split-window -v'
bind 'h' "swap-pane -s '{left-of}'"
bind 'j' "swap-pane -s '{down-of}'"
bind 'k' "swap-pane -s '{up-of}'"
bind 'l' "swap-pane -s '{right-of}'"
bind 'J' 'break-pane -a'
bind 'K' 'break-pane -b'
bind 'H' 'move-pane -t :-'
bind 'L' 'move-pane -t :+'
bind -n 'C-m' 'resize-pane -Z'
bind -n 'C-n' "send-keys 'C-l'"
bind -n 'C-b' 'copy-mode'
bind 'C-Space' 'select-pane -t :.+'

# layouts
bind '=' 'select-layout -E'

# copy mode
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor 'moonlight_dark'

run '~/.tmux/plugins/tpm/tpm'

# nvim-tmux-navigation
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'
bind-key -T copy-mode-vi 'C-h' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' 'select-pane -R'

# yazi-tmux-sequencing
is_yazi="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?yazi$'"
bind-key -n 'M-[' if-shell "$is_yazi" 'send-keys M-[' 'next-window'

# finish
display-message "TMUX config reloaded."
