# startup
set -s extended-keys on
set -s extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g focus-events on
set -s set-clipboard on
set -g mouse on
setw -g mode-keys vi

# leader
set -g prefix C-Space
bind 'C-Space' send-prefix
bind ',' source-file ~/.config/tmux/tmux.conf
bind '<' run ~/.tmux/plugins/tpm/bin/install_plugins

# linux support
unbind 'C-Enter'
bind-key -n 'C-PageDown' next-window
bind-key -n 'C-PageUp' previous-window
bind-key 'C-PageUp' swap-window -d -t -1
bind-key 'C-PageDown' swap-window -d -t +1

# macos support
unbind '['
unbind '{'
unbind '}'
bind-key -n 'M-[' previous-window
bind-key -n 'M-{' previous-window
bind-key -n 'M-}' next-window
bind-key 'M-{' swap-window -d -t -1
bind-key 'M-}' swap-window -d -t +1

# specials
bind 'C-Space' if-shell -F '#{==:#{session_name},jesugq}' \
  'switch-client -l' \
  'switch-client -t jesugq'
bind 'Space' if-shell -F '#{==:#{session_name},jesugq}' \
  'run-shell -C "move-window -t \"#{client_last_session}:\"; switch-client -t \"#{client_last_session}\""' \
  'move-window -t jesugq:; switch-client -t jesugq'

# sessions
unbind 'd'
bind 'C-d' detach-client
bind 'C-o' choose-tree -s
bind 'o' command-prompt "rename-session '%%'"

# windows
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
bind 'C-b' run 'tmux choose-tree -wf "##{==:##{session_name},#{session_name}}"'
bind 'b' command-prompt "rename-window '%%'"
bind 'n' 'new-window -a'
bind 'a' new-window -a '"$HOME/.script/snc"; "$HOME/.script/afk"'

# panes
unbind 'x'
unbind 'c'
bind 'C-w' run 'tmux choose-tree -t "#{pane_id}" -f "##{||:##{==:##{pane_id},#{pane_id}},##{>:##{window_panes},1}}" ; tmux send-keys -t "#{pane_id}" H'
bind 'w' select-pane -t :.+
bind 'q' if-shell -F '#{m/r:(sh|bash|zsh),#{pane_current_command}}' \
    kill-pane \
    'confirm-before -p "kill-pane #P? (y/n)" "kill-pane"'
bind 's' split-window -h
bind 'v' split-window -v

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor mirage
set -g status-position top
run '~/.tmux/plugins/tpm/tpm'

# copy mode
bind '/' if-shell -F '#{pane_in_mode}' 'send-keys -X cancel' 'copy-mode'
bind-key -T copy-mode-vi 'MouseDragEnd1Pane' send-keys -X copy-selection
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'V' send-keys -X select-line
bind-key -T copy-mode-vi 'C-v' send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection
bind-key -T copy-mode-vi 'Y' send-keys -X copy-line

# yazi-tmux-sequencing
is_yazi="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?yazi$'"
bind-key -n 'M-[' if-shell "$is_yazi" 'send-keys M-[' next-window

# finish
display-message "TMUX config reloaded."
